### ISSUE TITLE
Show Conversations Keeps Loading

### ISSUE THREAD

**Issue by ramizqazi** [evandavid/react-native-freshchat-sdk#2]
this is my code 

`
import React, { useEffect } from 'react';
import { Freshchat, FreshchatConfig } from 'react-native-freshchat-sdk';

import { Container, Text } from '../../common';

const freshchatConfig = new FreshchatConfig(
  '57297336-6774-4989-bc4c-3bf214a7ce8e',
  '7ac587ed-3a10-4edb-b8e9-0ee0aa738591',
);
Freshchat.init(freshchatConfig);

console.log(freshchatConfig);

/* =============================================================================
<SupportScreen />
============================================================================= */
const SupportScreen = () => {
  Freshchat.showConversations();
  return (
    <Container>
      <Text>Hello World</Text>
    </Container>
  );
};

/* Export
============================================================================= */
export default SupportScreen;
`
show conversation triggers the ui but it keeps loading forever.

**Comment by ravi-tally** [comment]
@ramizqazi In my case when I have added the domain then It's works fine for me 
```
var freshchatConfig = new FreshchatConfig(
      'APP_ID',
      'APP_KEY',
    );
    freshchatConfig.domain = 'YOUR_DOMAIN';
    Freshchat.init(freshchatConfig);
```
